-- Vincula as ilustrações da biblioteca de exercícios às imagens já
-- publicadas no Cloudflare R2 (bucket fitos-exercicios, publicado na raiz:
-- https://pub-76bc00d74c5a4bf98ccac51eb4c92de3.r2.dev/<arquivo>.webp — mesmo
-- padrão do importador `catalog:import-imagens-exercicios --public-only`,
-- ver docs/06-engenharia/arquitetura/ARMAZENAMENTO-DE-MIDIA-EXERCICIOS.md).
--
-- Roda no deploy (preDeploy `db:migrate:deploy`) porque o vínculo não pode
-- ser feito por SSH no Railway. Seguro e idempotente: só preenche
-- exercícios FITOS_CURATED globais que ainda estão SEM imagem; nunca troca
-- uma imagem existente, nunca cria nem apaga exercício, e não faz nada onde
-- o exercício não existe (bancos novos, testes).

-- 1) As 29 que faltavam: 5 antigas + 24 aeróbicos (arquivo ≠ chave nos aeróbicos).
WITH novas(external_id, arquivo) AS (VALUES
  ('fitos:alongamento-de-gluteo-deitado', 'alongamento-de-gluteo-deitado.webp'),
  ('fitos:barra-australiana', 'barra-australiana.webp'),
  ('fitos:elevacao-lateral-inclinada', 'elevacao-lateral-inclinada.webp'),
  ('fitos:panturrilha-no-leg-press', 'panturrilha-no-leg-press.webp'),
  ('fitos:rosca-scott-na-maquina', 'rosca-scott-na-maquina.webp'),
  ('fitos:aerobico-esteira-caminhada', 'caminhada-na-esteira.webp'),
  ('fitos:aerobico-esteira-inclinada', 'esteira-inclinada.webp'),
  ('fitos:aerobico-esteira-corrida', 'corrida-na-esteira.webp'),
  ('fitos:aerobico-bike', 'bike-ergometrica.webp'),
  ('fitos:aerobico-spinning', 'spinning.webp'),
  ('fitos:aerobico-eliptico', 'eliptico.webp'),
  ('fitos:aerobico-remo', 'remo-ergometrico.webp'),
  ('fitos:aerobico-corda', 'pular-corda.webp'),
  ('fitos:aerobico-escada', 'simulador-de-escadas.webp'),
  ('fitos:aerobico-caminhada-rua', 'caminhada-ao-ar-livre.webp'),
  ('fitos:aerobico-corrida-rua', 'corrida-ao-ar-livre.webp'),
  ('fitos:aerobico-natacao', 'natacao.webp'),
  ('fitos:aerobico-hidroginastica', 'hidroginastica.webp'),
  ('fitos:aerobico-bike-rua', 'ciclismo-ao-ar-livre.webp'),
  ('fitos:aerobico-trilha', 'trilha.webp'),
  ('fitos:aerobico-caminhada-nordica', 'caminhada-nordica.webp'),
  ('fitos:aerobico-circuito-funcional', 'circuito-funcional.webp'),
  ('fitos:aerobico-burpee', 'burpee.webp'),
  ('fitos:aerobico-polichinelo', 'polichinelo.webp'),
  ('fitos:aerobico-mountain-climber', 'mountain-climber.webp'),
  ('fitos:aerobico-skipping', 'skipping.webp'),
  ('fitos:aerobico-danca', 'danca-fitness.webp'),
  ('fitos:aerobico-boxe', 'boxe.webp'),
  ('fitos:aerobico-marcha', 'marcha-estacionaria.webp')
)
UPDATE "exercises" e
SET "imageUrl" = 'https://pub-76bc00d74c5a4bf98ccac51eb4c92de3.r2.dev/' || n.arquivo,
    "imageAlt" = e."name" || '. Ilustração da execução do movimento. Músculo principal: ' || COALESCE(e."muscle", 'corpo todo') || '. Equipamento: ' || COALESCE(e."equipments", 'nenhum') || '.',
    "updatedAt" = NOW()
FROM novas n
WHERE e."origin" = 'FITOS_CURATED'
  AND e."tenantId" IS NULL
  AND e."externalId" = n.external_id
  AND e."imageUrl" IS NULL
;

-- 2) As 203 do manifesto, caso ainda não tenham sido vinculadas no ambiente.
WITH manifesto(external_id, arquivo, alt) AS (VALUES
  ('fitos:abdominal-bicicleta', 'abdominal-bicicleta.webp', 'Abdominal bicicleta. Ilustração da execução do movimento. Músculo principal: Core. Equipamento: colchonete.'),
  ('fitos:abdominal-na-maquina', 'abdominal-na-maquina.webp', 'Abdominal na máquina. Ilustração da execução do movimento. Músculo principal: Core. Equipamento: máquina abdominal.'),
  ('fitos:abdominal-no-cabo-ajoelhado', 'abdominal-no-cabo-ajoelhado.webp', 'Abdominal no cabo ajoelhado. Ilustração da execução do movimento. Músculo principal: Core. Equipamento: polia alta, corda.'),
  ('fitos:abdominal-reverso', 'abdominal-reverso.webp', 'Abdominal reverso. Ilustração da execução do movimento. Músculo principal: Core. Equipamento: colchonete.'),
  ('fitos:abdominal-supra', 'abdominal-supra.webp', 'Abdominal supra. Ilustração da execução do movimento. Músculo principal: Core. Equipamento: colchonete.'),
  ('fitos:abducao-de-quadril-no-cabo', 'abducao-de-quadril-no-cabo.webp', 'Abdução de quadril no cabo. Ilustração da execução do movimento. Músculo principal: Glúteos. Equipamento: polia baixa, tornozeleira.'),
  ('fitos:abducao-lateral-deitada', 'abducao-lateral-deitada.webp', 'Abdução lateral deitada. Ilustração da execução do movimento. Músculo principal: Glúteos. Equipamento: colchonete.'),
  ('fitos:afundo-no-smith', 'afundo-no-smith.webp', 'Afundo no Smith. Ilustração da execução do movimento. Músculo principal: Quadríceps. Equipamento: máquina Smith.'),
  ('fitos:afundo-reverso', 'afundo-reverso.webp', 'Afundo reverso. Ilustração da execução do movimento. Músculo principal: Quadríceps. Equipamento: peso corporal.'),
  ('fitos:agachamento-bulgaro', 'agachamento-bulgaro.webp', 'Agachamento búlgaro. Ilustração da execução do movimento. Músculo principal: Quadríceps. Equipamento: halteres, banco.'),
  ('fitos:agachamento-com-salto', 'agachamento-com-salto.webp', 'Agachamento com salto. Ilustração da execução do movimento. Músculo principal: Quadríceps. Equipamento: peso corporal.'),
  ('fitos:agachamento-frontal-com-barra', 'agachamento-frontal-com-barra.webp', 'Agachamento frontal com barra. Ilustração da execução do movimento. Músculo principal: Quadríceps. Equipamento: barra, rack.'),
  ('fitos:agachamento-goblet', 'agachamento-goblet.webp', 'Agachamento goblet. Ilustração da execução do movimento. Músculo principal: Quadríceps. Equipamento: halter ou kettlebell.'),
  ('fitos:agachamento-hack', 'agachamento-hack.webp', 'Agachamento Hack. Ilustração da execução do movimento. Músculo principal: Quadríceps. Equipamento: máquina hack.'),
  ('fitos:agachamento-isometrico-na-parede', 'agachamento-isometrico-na-parede.webp', 'Agachamento isométrico na parede. Ilustração da execução do movimento. Músculo principal: Quadríceps. Equipamento: parede.'),
  ('fitos:agachamento-livre', 'agachamento-livre.webp', 'Agachamento livre. Ilustração da execução do movimento. Músculo principal: Quadríceps. Equipamento: peso corporal.'),
  ('fitos:agachamento-livre-com-barra', 'agachamento-livre-com-barra.webp', 'Agachamento livre com barra. Ilustração da execução do movimento. Músculo principal: Quadríceps. Equipamento: barra, rack.'),
  ('fitos:agachamento-no-cabo', 'agachamento-no-cabo.webp', 'Agachamento no cabo. Ilustração da execução do movimento. Músculo principal: Quadríceps. Equipamento: polia baixa.'),
  ('fitos:agachamento-no-smith', 'agachamento-no-smith.webp', 'Agachamento no Smith. Ilustração da execução do movimento. Músculo principal: Quadríceps. Equipamento: máquina Smith.'),
  ('fitos:agachamento-profundo-assistido', 'agachamento-profundo-assistido.webp', 'Agachamento profundo assistido. Ilustração da execução do movimento. Músculo principal: Mobilidade global. Equipamento: apoio fixo.'),
  ('fitos:agachamento-sumo-com-halter', 'agachamento-sumo-com-halter.webp', 'Agachamento sumô com halter. Ilustração da execução do movimento. Músculo principal: Glúteos. Equipamento: halter.'),
  ('fitos:alongamento-cruzado-de-ombro', 'alongamento-cruzado-de-ombro.webp', 'Alongamento cruzado de ombro. Ilustração da execução do movimento. Músculo principal: Mobilidade global. Equipamento: peso corporal.'),
  ('fitos:alongamento-de-adutores-borboleta', 'alongamento-de-adutores-borboleta.webp', 'Alongamento de adutores borboleta. Ilustração da execução do movimento. Músculo principal: Mobilidade global. Equipamento: colchonete.'),
  ('fitos:alongamento-de-biceps-na-parede', 'alongamento-de-biceps-na-parede.webp', 'Alongamento de bíceps na parede. Ilustração da execução do movimento. Músculo principal: Mobilidade global. Equipamento: parede.'),
  ('fitos:alongamento-de-dorsal-ajoelhado', 'alongamento-de-dorsal-ajoelhado.webp', 'Alongamento de dorsal ajoelhado. Ilustração da execução do movimento. Músculo principal: Mobilidade global. Equipamento: banco ou caixa.'),
  ('fitos:alongamento-de-extensores-do-punho', 'alongamento-de-extensores-do-punho.webp', 'Alongamento de extensores do punho. Ilustração da execução do movimento. Músculo principal: Mobilidade global. Equipamento: peso corporal.'),
  ('fitos:alongamento-de-flexores-do-punho', 'alongamento-de-flexores-do-punho.webp', 'Alongamento de flexores do punho. Ilustração da execução do movimento. Músculo principal: Mobilidade global. Equipamento: peso corporal.'),
  ('fitos:alongamento-de-panturrilha-na-parede', 'alongamento-de-panturrilha-na-parede.webp', 'Alongamento de panturrilha na parede. Ilustração da execução do movimento. Músculo principal: Mobilidade global. Equipamento: parede.'),
  ('fitos:alongamento-de-peitoral-na-parede', 'alongamento-de-peitoral-na-parede.webp', 'Alongamento de peitoral na parede. Ilustração da execução do movimento. Músculo principal: Mobilidade global. Equipamento: parede.'),
  ('fitos:alongamento-de-peitoral-na-porta', 'alongamento-de-peitoral-na-porta.webp', 'Alongamento de peitoral na porta. Ilustração da execução do movimento. Músculo principal: Mobilidade global. Equipamento: batente de porta.'),
  ('fitos:alongamento-de-posteriores-sentado', 'alongamento-de-posteriores-sentado.webp', 'Alongamento de posteriores sentado. Ilustração da execução do movimento. Músculo principal: Mobilidade global. Equipamento: colchonete.'),
  ('fitos:alongamento-de-quadriceps-em-pe', 'alongamento-de-quadriceps-em-pe.webp', 'Alongamento de quadríceps em pé. Ilustração da execução do movimento. Músculo principal: Mobilidade global. Equipamento: apoio opcional.'),
  ('fitos:alongamento-de-soleo-na-parede', 'alongamento-de-soleo-na-parede.webp', 'Alongamento de sóleo na parede. Ilustração da execução do movimento. Músculo principal: Mobilidade global. Equipamento: parede.'),
  ('fitos:alongamento-de-triceps-acima-da-cabeca', 'alongamento-de-triceps-acima-da-cabeca.webp', 'Alongamento de tríceps acima da cabeça. Ilustração da execução do movimento. Músculo principal: Mobilidade global. Equipamento: peso corporal.'),
  ('fitos:alongamento-do-flexor-do-quadril-ajoelhado', 'alongamento-do-flexor-do-quadril-ajoelhado.webp', 'Alongamento do flexor do quadril ajoelhado. Ilustração da execução do movimento. Músculo principal: Mobilidade global. Equipamento: colchonete.'),
  ('fitos:alongamento-piriforme-em-figura-quatro', 'alongamento-piriforme-em-figura-quatro.webp', 'Alongamento piriforme em figura quatro. Ilustração da execução do movimento. Músculo principal: Mobilidade global. Equipamento: colchonete.'),
  ('fitos:avanco-com-halteres', 'avanco-com-halteres.webp', 'Avanço com halteres. Ilustração da execução do movimento. Músculo principal: Quadríceps. Equipamento: halteres.'),
  ('fitos:avanco-lateral-com-halter', 'avanco-lateral-com-halter.webp', 'Avanço lateral com halter. Ilustração da execução do movimento. Músculo principal: Glúteos. Equipamento: halter.'),
  ('fitos:barra-fixa-neutra', 'barra-fixa-neutra.webp', 'Barra fixa neutra. Ilustração da execução do movimento. Músculo principal: Costas. Equipamento: barra fixa.'),
  ('fitos:barra-fixa-pronada', 'barra-fixa-pronada.webp', 'Barra fixa pronada. Ilustração da execução do movimento. Músculo principal: Costas. Equipamento: barra fixa.'),
  ('fitos:barra-fixa-supinada', 'barra-fixa-supinada.webp', 'Barra fixa supinada. Ilustração da execução do movimento. Músculo principal: Costas. Equipamento: barra fixa.'),
  ('fitos:bird-dog', 'bird-dog.webp', 'Bird dog. Ilustração da execução do movimento. Músculo principal: Core. Equipamento: colchonete.'),
  ('fitos:cadeira-extensora', 'cadeira-extensora.webp', 'Cadeira extensora. Ilustração da execução do movimento. Músculo principal: Quadríceps. Equipamento: cadeira extensora.'),
  ('fitos:cadeira-flexora', 'cadeira-flexora.webp', 'Cadeira flexora. Ilustração da execução do movimento. Músculo principal: Posteriores de coxa. Equipamento: cadeira flexora.'),
  ('fitos:cat-cow', 'cat-cow.webp', 'Cat-cow. Ilustração da execução do movimento. Músculo principal: Mobilidade global. Equipamento: colchonete.'),
  ('fitos:chest-press-sentado', 'chest-press-sentado.webp', 'Chest press sentado. Ilustração da execução do movimento. Músculo principal: Peitoral. Equipamento: máquina chest press.'),
  ('fitos:cobra-suave', 'cobra-suave.webp', 'Cobra suave. Ilustração da execução do movimento. Músculo principal: Mobilidade global. Equipamento: colchonete.'),
  ('fitos:coice-na-maquina', 'coice-na-maquina.webp', 'Coice na máquina. Ilustração da execução do movimento. Músculo principal: Glúteos. Equipamento: máquina de glúteos.'),
  ('fitos:coice-no-cabo', 'coice-no-cabo.webp', 'Coice no cabo. Ilustração da execução do movimento. Músculo principal: Glúteos. Equipamento: polia baixa, tornozeleira.'),
  ('fitos:crossover-alto', 'crossover-alto.webp', 'Crossover alto. Ilustração da execução do movimento. Músculo principal: Peitoral. Equipamento: polia dupla.'),
  ('fitos:crossover-baixo', 'crossover-baixo.webp', 'Crossover baixo. Ilustração da execução do movimento. Músculo principal: Peitoral. Equipamento: polia dupla.'),
  ('fitos:crossover-medio', 'crossover-medio.webp', 'Crossover médio. Ilustração da execução do movimento. Músculo principal: Peitoral. Equipamento: polia dupla.'),
  ('fitos:crucifixo-inclinado-com-halteres', 'crucifixo-inclinado-com-halteres.webp', 'Crucifixo inclinado com halteres. Ilustração da execução do movimento. Músculo principal: Peitoral. Equipamento: halteres, banco inclinado.'),
  ('fitos:crucifixo-inverso-com-halteres', 'crucifixo-inverso-com-halteres.webp', 'Crucifixo inverso com halteres. Ilustração da execução do movimento. Músculo principal: Ombros. Equipamento: halteres.'),
  ('fitos:crucifixo-inverso-na-maquina', 'crucifixo-inverso-na-maquina.webp', 'Crucifixo inverso na máquina. Ilustração da execução do movimento. Músculo principal: Ombros. Equipamento: máquina peck deck invertida.'),
  ('fitos:crucifixo-inverso-no-cabo', 'crucifixo-inverso-no-cabo.webp', 'Crucifixo inverso no cabo. Ilustração da execução do movimento. Músculo principal: Ombros. Equipamento: polia dupla.'),
  ('fitos:crucifixo-na-maquina-peck-deck', 'crucifixo-na-maquina-peck-deck.webp', 'Crucifixo na máquina peck deck. Ilustração da execução do movimento. Músculo principal: Peitoral. Equipamento: máquina peck deck.'),
  ('fitos:crucifixo-reto-com-halteres', 'crucifixo-reto-com-halteres.webp', 'Crucifixo reto com halteres. Ilustração da execução do movimento. Músculo principal: Peitoral. Equipamento: halteres, banco reto.'),
  ('fitos:crucifixo-unilateral-no-cabo', 'crucifixo-unilateral-no-cabo.webp', 'Crucifixo unilateral no cabo. Ilustração da execução do movimento. Músculo principal: Peitoral. Equipamento: polia.'),
  ('fitos:dead-bug', 'dead-bug.webp', 'Dead bug. Ilustração da execução do movimento. Músculo principal: Core. Equipamento: colchonete.'),
  ('fitos:desenvolvimento-arnold', 'desenvolvimento-arnold.webp', 'Desenvolvimento Arnold. Ilustração da execução do movimento. Músculo principal: Ombros. Equipamento: halteres.'),
  ('fitos:desenvolvimento-com-halteres-sentado', 'desenvolvimento-com-halteres-sentado.webp', 'Desenvolvimento com halteres sentado. Ilustração da execução do movimento. Músculo principal: Ombros. Equipamento: halteres, banco.'),
  ('fitos:desenvolvimento-militar-com-barra', 'desenvolvimento-militar-com-barra.webp', 'Desenvolvimento militar com barra. Ilustração da execução do movimento. Músculo principal: Ombros. Equipamento: barra.'),
  ('fitos:desenvolvimento-na-maquina', 'desenvolvimento-na-maquina.webp', 'Desenvolvimento na máquina. Ilustração da execução do movimento. Músculo principal: Ombros. Equipamento: máquina de desenvolvimento.'),
  ('fitos:desenvolvimento-no-cabo', 'desenvolvimento-no-cabo.webp', 'Desenvolvimento no cabo. Ilustração da execução do movimento. Músculo principal: Ombros. Equipamento: polia baixa.'),
  ('fitos:donkey-kick', 'donkey-kick.webp', 'Donkey kick. Ilustração da execução do movimento. Músculo principal: Glúteos. Equipamento: colchonete.'),
  ('fitos:elevacao-de-joelhos-na-barra', 'elevacao-de-joelhos-na-barra.webp', 'Elevação de joelhos na barra. Ilustração da execução do movimento. Músculo principal: Core. Equipamento: barra fixa.'),
  ('fitos:elevacao-de-pernas-deitado', 'elevacao-de-pernas-deitado.webp', 'Elevação de pernas deitado. Ilustração da execução do movimento. Músculo principal: Core. Equipamento: colchonete.'),
  ('fitos:elevacao-de-pernas-na-barra', 'elevacao-de-pernas-na-barra.webp', 'Elevação de pernas na barra. Ilustração da execução do movimento. Músculo principal: Core. Equipamento: barra fixa.'),
  ('fitos:elevacao-em-y-no-cabo', 'elevacao-em-y-no-cabo.webp', 'Elevação em Y no cabo. Ilustração da execução do movimento. Músculo principal: Ombros. Equipamento: polia baixa.'),
  ('fitos:elevacao-frontal-com-barra', 'elevacao-frontal-com-barra.webp', 'Elevação frontal com barra. Ilustração da execução do movimento. Músculo principal: Ombros. Equipamento: barra.'),
  ('fitos:elevacao-frontal-com-halteres', 'elevacao-frontal-com-halteres.webp', 'Elevação frontal com halteres. Ilustração da execução do movimento. Músculo principal: Ombros. Equipamento: halteres.'),
  ('fitos:elevacao-frontal-no-cabo', 'elevacao-frontal-no-cabo.webp', 'Elevação frontal no cabo. Ilustração da execução do movimento. Músculo principal: Ombros. Equipamento: polia baixa.'),
  ('fitos:elevacao-lateral-com-halteres', 'elevacao-lateral-com-halteres.webp', 'Elevação lateral com halteres. Ilustração da execução do movimento. Músculo principal: Ombros. Equipamento: halteres.'),
  ('fitos:elevacao-lateral-na-maquina', 'elevacao-lateral-na-maquina.webp', 'Elevação lateral na máquina. Ilustração da execução do movimento. Músculo principal: Ombros. Equipamento: máquina de elevação lateral.'),
  ('fitos:elevacao-lateral-no-cabo', 'elevacao-lateral-no-cabo.webp', 'Elevação lateral no cabo. Ilustração da execução do movimento. Músculo principal: Ombros. Equipamento: polia baixa.'),
  ('fitos:elevacao-pelvica-com-barra', 'elevacao-pelvica-com-barra.webp', 'Elevação pélvica com barra. Ilustração da execução do movimento. Músculo principal: Glúteos. Equipamento: barra, banco.'),
  ('fitos:elevacao-pelvica-na-maquina', 'elevacao-pelvica-na-maquina.webp', 'Elevação pélvica na máquina. Ilustração da execução do movimento. Músculo principal: Glúteos. Equipamento: máquina de hip thrust.'),
  ('fitos:encolhimento-com-barra', 'encolhimento-com-barra.webp', 'Encolhimento com barra. Ilustração da execução do movimento. Músculo principal: Trapézio e antebraços. Equipamento: barra.'),
  ('fitos:encolhimento-com-halteres', 'encolhimento-com-halteres.webp', 'Encolhimento com halteres. Ilustração da execução do movimento. Músculo principal: Trapézio e antebraços. Equipamento: halteres.'),
  ('fitos:encolhimento-na-maquina', 'encolhimento-na-maquina.webp', 'Encolhimento na máquina. Ilustração da execução do movimento. Músculo principal: Trapézio e antebraços. Equipamento: máquina de encolhimento.'),
  ('fitos:encolhimento-no-cabo', 'encolhimento-no-cabo.webp', 'Encolhimento no cabo. Ilustração da execução do movimento. Músculo principal: Trapézio e antebraços. Equipamento: polia baixa, barra.'),
  ('fitos:extensao-de-triceps-na-maquina', 'extensao-de-triceps-na-maquina.webp', 'Extensão de tríceps na máquina. Ilustração da execução do movimento. Músculo principal: Tríceps. Equipamento: máquina de tríceps.'),
  ('fitos:extensao-lombar-no-banco-romano', 'extensao-lombar-no-banco-romano.webp', 'Extensão lombar no banco romano. Ilustração da execução do movimento. Músculo principal: Costas. Equipamento: banco romano.'),
  ('fitos:extensao-toracica-no-rolo', 'extensao-toracica-no-rolo.webp', 'Extensão torácica no rolo. Ilustração da execução do movimento. Músculo principal: Mobilidade global. Equipamento: rolo de liberação.'),
  ('fitos:face-pull', 'face-pull.webp', 'Face pull. Ilustração da execução do movimento. Músculo principal: Costas. Equipamento: polia alta, corda.'),
  ('fitos:farmer-walk', 'farmer-walk.webp', 'Farmer walk. Ilustração da execução do movimento. Músculo principal: Core. Equipamento: halteres ou kettlebells.'),
  ('fitos:fire-hydrant', 'fire-hydrant.webp', 'Fire hydrant. Ilustração da execução do movimento. Músculo principal: Glúteos. Equipamento: colchonete.'),
  ('fitos:flexao-arqueiro', 'flexao-arqueiro.webp', 'Flexão arqueiro. Ilustração da execução do movimento. Músculo principal: Peitoral. Equipamento: peso corporal.'),
  ('fitos:flexao-de-bracos', 'flexao-de-bracos.webp', 'Flexão de braços. Ilustração da execução do movimento. Músculo principal: Peitoral. Equipamento: peso corporal.'),
  ('fitos:flexao-de-joelhos-no-cabo', 'flexao-de-joelhos-no-cabo.webp', 'Flexão de joelhos no cabo. Ilustração da execução do movimento. Músculo principal: Posteriores de coxa. Equipamento: polia baixa, tornozeleira.'),
  ('fitos:flexao-declinada', 'flexao-declinada.webp', 'Flexão declinada. Ilustração da execução do movimento. Músculo principal: Peitoral. Equipamento: apoio para os pés.'),
  ('fitos:flexao-diamante', 'flexao-diamante.webp', 'Flexão diamante. Ilustração da execução do movimento. Músculo principal: Peitoral. Equipamento: peso corporal.'),
  ('fitos:flexao-inclinada', 'flexao-inclinada.webp', 'Flexão inclinada. Ilustração da execução do movimento. Músculo principal: Peitoral. Equipamento: apoio elevado.'),
  ('fitos:flexao-pike', 'flexao-pike.webp', 'Flexão pike. Ilustração da execução do movimento. Músculo principal: Ombros. Equipamento: peso corporal.'),
  ('fitos:flexora-em-pe-unilateral', 'flexora-em-pe-unilateral.webp', 'Flexora em pé unilateral. Ilustração da execução do movimento. Músculo principal: Posteriores de coxa. Equipamento: máquina flexora em pé.'),
  ('fitos:good-morning-com-barra', 'good-morning-com-barra.webp', 'Good morning com barra. Ilustração da execução do movimento. Músculo principal: Posteriores de coxa. Equipamento: barra.'),
  ('fitos:hollow-body-hold', 'hollow-body-hold.webp', 'Hollow body hold. Ilustração da execução do movimento. Músculo principal: Core. Equipamento: colchonete.'),
  ('fitos:leg-press-45', 'leg-press-45.webp', 'Leg press 45°. Ilustração em duas fases do movimento (início e final). Músculo principal: Quadríceps. Equipamento: leg press 45°.'),
  ('fitos:leg-press-horizontal', 'leg-press-horizontal.webp', 'Leg press horizontal. Ilustração da execução do movimento. Músculo principal: Quadríceps. Equipamento: leg press horizontal.'),
  ('fitos:levantamento-terra-convencional', 'levantamento-terra-convencional.webp', 'Levantamento terra convencional. Ilustração da execução do movimento. Músculo principal: Costas. Equipamento: barra, anilhas.'),
  ('fitos:levantamento-terra-romeno-com-barra', 'levantamento-terra-romeno-com-barra.webp', 'Levantamento terra romeno com barra. Ilustração da execução do movimento. Músculo principal: Posteriores de coxa. Equipamento: barra.'),
  ('fitos:levantamento-terra-romeno-com-halteres', 'levantamento-terra-romeno-com-halteres.webp', 'Levantamento terra romeno com halteres. Ilustração da execução do movimento. Músculo principal: Posteriores de coxa. Equipamento: halteres.'),
  ('fitos:levantamento-terra-sumo', 'levantamento-terra-sumo.webp', 'Levantamento terra sumô. Ilustração da execução do movimento. Músculo principal: Costas. Equipamento: barra, anilhas.'),
  ('fitos:maquina-abdutora', 'maquina-abdutora.webp', 'Máquina abdutora. Ilustração da execução do movimento. Músculo principal: Glúteos. Equipamento: máquina abdutora.'),
  ('fitos:mergulho-entre-bancos', 'mergulho-entre-bancos.webp', 'Mergulho entre bancos. Ilustração da execução do movimento. Músculo principal: Tríceps. Equipamento: dois bancos.'),
  ('fitos:mergulho-na-maquina', 'mergulho-na-maquina.webp', 'Mergulho na máquina. Ilustração da execução do movimento. Músculo principal: Tríceps. Equipamento: máquina de mergulho.'),
  ('fitos:mesa-flexora', 'mesa-flexora.webp', 'Mesa flexora. Ilustração da execução do movimento. Músculo principal: Posteriores de coxa. Equipamento: mesa flexora.'),
  ('fitos:mobilidade-90-90-de-quadril', 'mobilidade-90-90-de-quadril.webp', 'Mobilidade 90/90 de quadril. Ilustração da execução do movimento. Músculo principal: Mobilidade global. Equipamento: colchonete.'),
  ('fitos:mobilidade-de-ombro-com-bastao', 'mobilidade-de-ombro-com-bastao.webp', 'Mobilidade de ombro com bastão. Ilustração da execução do movimento. Músculo principal: Mobilidade global. Equipamento: bastão.'),
  ('fitos:mobilidade-de-tornozelo-na-parede', 'mobilidade-de-tornozelo-na-parede.webp', 'Mobilidade de tornozelo na parede. Ilustração da execução do movimento. Músculo principal: Mobilidade global. Equipamento: parede.'),
  ('fitos:nordic-curl-assistido', 'nordic-curl-assistido.webp', 'Nordic curl assistido. Ilustração da execução do movimento. Músculo principal: Posteriores de coxa. Equipamento: apoio para os pés.'),
  ('fitos:pallof-press', 'pallof-press.webp', 'Pallof press. Ilustração da execução do movimento. Músculo principal: Core. Equipamento: polia.'),
  ('fitos:panturrilha-bilateral-no-solo', 'panturrilha-bilateral-no-solo.webp', 'Panturrilha bilateral no solo. Ilustração da execução do movimento. Músculo principal: Panturrilhas. Equipamento: peso corporal.'),
  ('fitos:panturrilha-em-pe-com-halteres', 'panturrilha-em-pe-com-halteres.webp', 'Panturrilha em pé com halteres. Ilustração da execução do movimento. Músculo principal: Panturrilhas. Equipamento: halteres.'),
  ('fitos:panturrilha-em-pe-na-maquina', 'panturrilha-em-pe-na-maquina.webp', 'Panturrilha em pé na máquina. Ilustração da execução do movimento. Músculo principal: Panturrilhas. Equipamento: máquina de panturrilha.'),
  ('fitos:panturrilha-no-smith', 'panturrilha-no-smith.webp', 'Panturrilha no Smith. Ilustração da execução do movimento. Músculo principal: Panturrilhas. Equipamento: máquina Smith, plataforma.'),
  ('fitos:panturrilha-sentada-na-maquina', 'panturrilha-sentada-na-maquina.webp', 'Panturrilha sentada na máquina. Ilustração da execução do movimento. Músculo principal: Panturrilhas. Equipamento: máquina de panturrilha sentada.'),
  ('fitos:panturrilha-sentado-com-barra', 'panturrilha-sentado-com-barra.webp', 'Panturrilha sentado com barra. Ilustração da execução do movimento. Músculo principal: Panturrilhas. Equipamento: barra, banco.'),
  ('fitos:panturrilha-unilateral-em-degrau', 'panturrilha-unilateral-em-degrau.webp', 'Panturrilha unilateral em degrau. Ilustração da execução do movimento. Músculo principal: Panturrilhas. Equipamento: degrau.'),
  ('fitos:parada-de-maos-assistida', 'parada-de-maos-assistida.webp', 'Parada de mãos assistida. Ilustração da execução do movimento. Músculo principal: Ombros. Equipamento: parede.'),
  ('fitos:paralelas-com-foco-em-triceps', 'paralelas-com-foco-em-triceps.webp', 'Paralelas com foco em tríceps. Ilustração da execução do movimento. Músculo principal: Tríceps. Equipamento: barras paralelas.'),
  ('fitos:paralelas-com-foco-no-peitoral', 'paralelas-com-foco-no-peitoral.webp', 'Paralelas com foco no peitoral. Ilustração da execução do movimento. Músculo principal: Peitoral. Equipamento: barras paralelas.'),
  ('fitos:passada-com-barra', 'passada-com-barra.webp', 'Passada com barra. Ilustração da execução do movimento. Músculo principal: Quadríceps. Equipamento: barra.'),
  ('fitos:pinca-de-anilhas', 'pinca-de-anilhas.webp', 'Pinça de anilhas. Ilustração da execução do movimento. Músculo principal: Trapézio e antebraços. Equipamento: anilhas.'),
  ('fitos:pistol-squat-assistido', 'pistol-squat-assistido.webp', 'Pistol squat assistido. Ilustração da execução do movimento. Músculo principal: Quadríceps. Equipamento: apoio fixo.'),
  ('fitos:ponte-com-caminhada-dos-calcanhares', 'ponte-com-caminhada-dos-calcanhares.webp', 'Ponte com caminhada dos calcanhares. Ilustração da execução do movimento. Músculo principal: Posteriores de coxa. Equipamento: colchonete.'),
  ('fitos:ponte-de-gluteos', 'ponte-de-gluteos.webp', 'Ponte de glúteos. Ilustração da execução do movimento. Músculo principal: Glúteos. Equipamento: colchonete.'),
  ('fitos:ponte-de-gluteos-com-halter', 'ponte-de-gluteos-com-halter.webp', 'Ponte de glúteos com halter. Ilustração da execução do movimento. Músculo principal: Glúteos. Equipamento: halter, colchonete.'),
  ('fitos:ponte-unilateral', 'ponte-unilateral.webp', 'Ponte unilateral. Ilustração da execução do movimento. Músculo principal: Glúteos. Equipamento: colchonete.'),
  ('fitos:postura-da-crianca', 'postura-da-crianca.webp', 'Postura da criança. Ilustração da execução do movimento. Músculo principal: Mobilidade global. Equipamento: colchonete.'),
  ('fitos:prancha-com-toque-nos-ombros', 'prancha-com-toque-nos-ombros.webp', 'Prancha com toque nos ombros. Ilustração da execução do movimento. Músculo principal: Core. Equipamento: colchonete.'),
  ('fitos:prancha-frontal', 'prancha-frontal.webp', 'Prancha frontal. Ilustração da execução do movimento. Músculo principal: Core. Equipamento: colchonete.'),
  ('fitos:prancha-lateral', 'prancha-lateral.webp', 'Prancha lateral. Ilustração da execução do movimento. Músculo principal: Core. Equipamento: colchonete.'),
  ('fitos:pull-through-no-cabo', 'pull-through-no-cabo.webp', 'Pull-through no cabo. Ilustração da execução do movimento. Músculo principal: Posteriores de coxa. Equipamento: polia baixa, corda.'),
  ('fitos:pulldown-com-bracos-estendidos', 'pulldown-com-bracos-estendidos.webp', 'Pulldown com braços estendidos. Ilustração da execução do movimento. Músculo principal: Costas. Equipamento: polia alta, barra.'),
  ('fitos:pullover-com-halter', 'pullover-com-halter.webp', 'Pullover com halter. Ilustração da execução do movimento. Músculo principal: Peitoral. Equipamento: halter, banco.'),
  ('fitos:puxada-alta-pegada-aberta', 'puxada-alta-pegada-aberta.webp', 'Puxada alta pegada aberta. Ilustração da execução do movimento. Músculo principal: Costas. Equipamento: polia alta, barra.'),
  ('fitos:puxada-alta-pegada-neutra', 'puxada-alta-pegada-neutra.webp', 'Puxada alta pegada neutra. Ilustração da execução do movimento. Músculo principal: Costas. Equipamento: polia alta, triângulo.'),
  ('fitos:puxada-alta-pegada-supinada', 'puxada-alta-pegada-supinada.webp', 'Puxada alta pegada supinada. Ilustração da execução do movimento. Músculo principal: Costas. Equipamento: polia alta, barra.'),
  ('fitos:puxada-frontal-na-maquina', 'puxada-frontal-na-maquina.webp', 'Puxada frontal na máquina. Ilustração da execução do movimento. Músculo principal: Costas. Equipamento: máquina de puxada.'),
  ('fitos:puxada-unilateral-no-cabo', 'puxada-unilateral-no-cabo.webp', 'Puxada unilateral no cabo. Ilustração da execução do movimento. Músculo principal: Costas. Equipamento: polia alta.'),
  ('fitos:remada-alta-com-barra', 'remada-alta-com-barra.webp', 'Remada alta com barra. Ilustração da execução do movimento. Músculo principal: Ombros. Equipamento: barra.'),
  ('fitos:remada-alta-no-cabo', 'remada-alta-no-cabo.webp', 'Remada alta no cabo. Ilustração da execução do movimento. Músculo principal: Ombros. Equipamento: polia baixa, barra.'),
  ('fitos:remada-articulada', 'remada-articulada.webp', 'Remada articulada. Ilustração da execução do movimento. Músculo principal: Costas. Equipamento: máquina articulada.'),
  ('fitos:remada-baixa-com-barra-reta', 'remada-baixa-com-barra-reta.webp', 'Remada baixa com barra reta. Ilustração da execução do movimento. Músculo principal: Costas. Equipamento: polia baixa, barra.'),
  ('fitos:remada-baixa-na-maquina', 'remada-baixa-na-maquina.webp', 'Remada baixa na máquina. Ilustração da execução do movimento. Músculo principal: Costas. Equipamento: máquina de remada.'),
  ('fitos:remada-baixa-no-cabo', 'remada-baixa-no-cabo.webp', 'Remada baixa no cabo. Ilustração da execução do movimento. Músculo principal: Costas. Equipamento: polia baixa, triângulo.'),
  ('fitos:remada-cavalinho', 'remada-cavalinho.webp', 'Remada cavalinho. Ilustração da execução do movimento. Músculo principal: Costas. Equipamento: barra, suporte landmine.'),
  ('fitos:remada-com-halteres-no-banco-inclinado', 'remada-com-halteres-no-banco-inclinado.webp', 'Remada com halteres no banco inclinado. Ilustração da execução do movimento. Músculo principal: Costas. Equipamento: halteres, banco inclinado.'),
  ('fitos:remada-curvada-com-barra', 'remada-curvada-com-barra.webp', 'Remada curvada com barra. Ilustração da execução do movimento. Músculo principal: Costas. Equipamento: barra.'),
  ('fitos:remada-pendlay', 'remada-pendlay.webp', 'Remada Pendlay. Ilustração da execução do movimento. Músculo principal: Costas. Equipamento: barra.'),
  ('fitos:remada-unilateral-com-halter', 'remada-unilateral-com-halter.webp', 'Remada unilateral com halter. Ilustração da execução do movimento. Músculo principal: Costas. Equipamento: halter, banco.'),
  ('fitos:remada-unilateral-no-cabo', 'remada-unilateral-no-cabo.webp', 'Remada unilateral no cabo. Ilustração da execução do movimento. Músculo principal: Costas. Equipamento: polia.'),
  ('fitos:rosca-alta-no-cabo', 'rosca-alta-no-cabo.webp', 'Rosca alta no cabo. Ilustração da execução do movimento. Músculo principal: Bíceps. Equipamento: polia dupla.'),
  ('fitos:rosca-alternada-com-halteres', 'rosca-alternada-com-halteres.webp', 'Rosca alternada com halteres. Ilustração da execução do movimento. Músculo principal: Bíceps. Equipamento: halteres.'),
  ('fitos:rosca-aranha-com-barra-w', 'rosca-aranha-com-barra-w.webp', 'Rosca aranha com barra W. Ilustração da execução do movimento. Músculo principal: Bíceps. Equipamento: barra W, banco inclinado.'),
  ('fitos:rosca-com-corda-no-cabo', 'rosca-com-corda-no-cabo.webp', 'Rosca com corda no cabo. Ilustração da execução do movimento. Músculo principal: Bíceps. Equipamento: polia baixa, corda.'),
  ('fitos:rosca-concentrada', 'rosca-concentrada.webp', 'Rosca concentrada. Ilustração da execução do movimento. Músculo principal: Bíceps. Equipamento: halter, banco.'),
  ('fitos:rosca-de-punho-com-barra', 'rosca-de-punho-com-barra.webp', 'Rosca de punho com barra. Ilustração da execução do movimento. Músculo principal: Trapézio e antebraços. Equipamento: barra, banco.'),
  ('fitos:rosca-direta-com-barra', 'rosca-direta-com-barra.webp', 'Rosca direta com barra. Ilustração da execução do movimento. Músculo principal: Bíceps. Equipamento: barra.'),
  ('fitos:rosca-direta-com-barra-w', 'rosca-direta-com-barra-w.webp', 'Rosca direta com barra W. Ilustração em duas fases do movimento (início e final). Músculo principal: Bíceps. Equipamento: barra W.'),
  ('fitos:rosca-direta-na-maquina', 'rosca-direta-na-maquina.webp', 'Rosca direta na máquina. Ilustração da execução do movimento. Músculo principal: Bíceps. Equipamento: máquina de rosca.'),
  ('fitos:rosca-direta-no-cabo', 'rosca-direta-no-cabo.webp', 'Rosca direta no cabo. Ilustração da execução do movimento. Músculo principal: Bíceps. Equipamento: polia baixa, barra.'),
  ('fitos:rosca-inclinada-com-halteres', 'rosca-inclinada-com-halteres.webp', 'Rosca inclinada com halteres. Ilustração da execução do movimento. Músculo principal: Bíceps. Equipamento: halteres, banco inclinado.'),
  ('fitos:rosca-inversa-com-barra-w', 'rosca-inversa-com-barra-w.webp', 'Rosca inversa com barra W. Ilustração da execução do movimento. Músculo principal: Trapézio e antebraços. Equipamento: barra W.'),
  ('fitos:rosca-inversa-de-punho-com-barra', 'rosca-inversa-de-punho-com-barra.webp', 'Rosca inversa de punho com barra. Ilustração da execução do movimento. Músculo principal: Trapézio e antebraços. Equipamento: barra, banco.'),
  ('fitos:rosca-martelo', 'rosca-martelo.webp', 'Rosca martelo. Ilustração da execução do movimento. Músculo principal: Bíceps. Equipamento: halteres.'),
  ('fitos:rosca-martelo-inclinada', 'rosca-martelo-inclinada.webp', 'Rosca martelo inclinada. Ilustração da execução do movimento. Músculo principal: Bíceps. Equipamento: halteres, banco inclinado.'),
  ('fitos:rosca-scott-com-barra-w', 'rosca-scott-com-barra-w.webp', 'Rosca Scott com barra W. Ilustração da execução do movimento. Músculo principal: Bíceps. Equipamento: barra W, banco Scott.'),
  ('fitos:rosca-unilateral-no-cabo', 'rosca-unilateral-no-cabo.webp', 'Rosca unilateral no cabo. Ilustração da execução do movimento. Músculo principal: Bíceps. Equipamento: polia baixa.'),
  ('fitos:rosca-zottman', 'rosca-zottman.webp', 'Rosca Zottman. Ilustração da execução do movimento. Músculo principal: Bíceps. Equipamento: halteres.'),
  ('fitos:rotacao-de-punho-com-halter', 'rotacao-de-punho-com-halter.webp', 'Rotação de punho com halter. Ilustração da execução do movimento. Músculo principal: Trapézio e antebraços. Equipamento: halter.'),
  ('fitos:rotacao-de-tronco-na-maquina', 'rotacao-de-tronco-na-maquina.webp', 'Rotação de tronco na máquina. Ilustração da execução do movimento. Músculo principal: Core. Equipamento: máquina de rotação.'),
  ('fitos:rotacao-externa-de-ombro-com-apoio', 'rotacao-externa-de-ombro-com-apoio.webp', 'Rotação externa de ombro com apoio. Ilustração da execução do movimento. Músculo principal: Mobilidade global. Equipamento: parede.'),
  ('fitos:rotacao-lombar-deitada', 'rotacao-lombar-deitada.webp', 'Rotação lombar deitada. Ilustração da execução do movimento. Músculo principal: Mobilidade global. Equipamento: colchonete.'),
  ('fitos:rotacao-toracica-em-quatro-apoios', 'rotacao-toracica-em-quatro-apoios.webp', 'Rotação torácica em quatro apoios. Ilustração da execução do movimento. Músculo principal: Mobilidade global. Equipamento: colchonete.'),
  ('fitos:step-up-com-halteres', 'step-up-com-halteres.webp', 'Step-up com halteres. Ilustração da execução do movimento. Músculo principal: Quadríceps. Equipamento: halteres, caixa.'),
  ('fitos:stiff-com-barra', 'stiff-com-barra.webp', 'Stiff com barra. Ilustração da execução do movimento. Músculo principal: Posteriores de coxa. Equipamento: barra.'),
  ('fitos:suitcase-carry-unilateral', 'suitcase-carry-unilateral.webp', 'Suitcase carry unilateral. Ilustração da execução do movimento. Músculo principal: Core. Equipamento: halter ou kettlebell.'),
  ('fitos:superman', 'superman.webp', 'Superman. Ilustração da execução do movimento. Músculo principal: Costas. Equipamento: colchonete.'),
  ('fitos:supino-com-pegada-fechada', 'supino-com-pegada-fechada.webp', 'Supino com pegada fechada. Ilustração da execução do movimento. Músculo principal: Peitoral. Equipamento: barra, banco reto.'),
  ('fitos:supino-declinado-com-barra', 'supino-declinado-com-barra.webp', 'Supino declinado com barra. Ilustração da execução do movimento. Músculo principal: Peitoral. Equipamento: barra, banco declinado.'),
  ('fitos:supino-declinado-com-halteres', 'supino-declinado-com-halteres.webp', 'Supino declinado com halteres. Ilustração da execução do movimento. Músculo principal: Peitoral. Equipamento: halteres, banco declinado.'),
  ('fitos:supino-declinado-na-maquina', 'supino-declinado-na-maquina.webp', 'Supino declinado na máquina. Ilustração da execução do movimento. Músculo principal: Peitoral. Equipamento: máquina de supino declinado.'),
  ('fitos:supino-inclinado-com-barra', 'supino-inclinado-com-barra.webp', 'Supino inclinado com barra. Ilustração da execução do movimento. Músculo principal: Peitoral. Equipamento: barra, banco inclinado.'),
  ('fitos:supino-inclinado-com-halteres', 'supino-inclinado-com-halteres.webp', 'Supino inclinado com halteres. Ilustração da execução do movimento. Músculo principal: Peitoral. Equipamento: halteres, banco inclinado.'),
  ('fitos:supino-inclinado-na-maquina', 'supino-inclinado-na-maquina.webp', 'Supino inclinado na máquina. Ilustração da execução do movimento. Músculo principal: Peitoral. Equipamento: máquina de supino inclinado.'),
  ('fitos:supino-reto-com-barra', 'supino-reto-com-barra.webp', 'Supino reto com barra. Ilustração da execução do movimento. Músculo principal: Peitoral. Equipamento: barra, banco reto.'),
  ('fitos:supino-reto-com-halteres', 'supino-reto-com-halteres.webp', 'Supino reto com halteres. Ilustração da execução do movimento. Músculo principal: Peitoral. Equipamento: halteres, banco reto.'),
  ('fitos:suspensao-na-barra', 'suspensao-na-barra.webp', 'Suspensão na barra. Ilustração da execução do movimento. Músculo principal: Trapézio e antebraços. Equipamento: barra fixa.'),
  ('fitos:terra-romeno-no-smith', 'terra-romeno-no-smith.webp', 'Terra romeno no Smith. Ilustração da execução do movimento. Músculo principal: Posteriores de coxa. Equipamento: máquina Smith.'),
  ('fitos:triceps-coice-com-halter', 'triceps-coice-com-halter.webp', 'Tríceps coice com halter. Ilustração da execução do movimento. Músculo principal: Tríceps. Equipamento: halter, banco.'),
  ('fitos:triceps-frances-com-halter', 'triceps-frances-com-halter.webp', 'Tríceps francês com halter. Ilustração da execução do movimento. Músculo principal: Tríceps. Equipamento: halter.'),
  ('fitos:triceps-frances-no-cabo', 'triceps-frances-no-cabo.webp', 'Tríceps francês no cabo. Ilustração da execução do movimento. Músculo principal: Tríceps. Equipamento: polia, corda.'),
  ('fitos:triceps-na-polia-com-barra', 'triceps-na-polia-com-barra.webp', 'Tríceps na polia com barra. Ilustração da execução do movimento. Músculo principal: Tríceps. Equipamento: polia alta, barra.'),
  ('fitos:triceps-na-polia-com-corda', 'triceps-na-polia-com-corda.webp', 'Tríceps na polia com corda. Ilustração da execução do movimento. Músculo principal: Tríceps. Equipamento: polia alta, corda.'),
  ('fitos:triceps-testa-com-barra-w', 'triceps-testa-com-barra-w.webp', 'Tríceps testa com barra W. Ilustração da execução do movimento. Músculo principal: Tríceps. Equipamento: barra W, banco.'),
  ('fitos:triceps-testa-no-cabo', 'triceps-testa-no-cabo.webp', 'Tríceps testa no cabo. Ilustração da execução do movimento. Músculo principal: Tríceps. Equipamento: polia, barra.'),
  ('fitos:triceps-unilateral-no-cabo', 'triceps-unilateral-no-cabo.webp', 'Tríceps unilateral no cabo. Ilustração da execução do movimento. Músculo principal: Tríceps. Equipamento: polia alta.'),
  ('fitos:wood-chop-alto-para-baixo', 'wood-chop-alto-para-baixo.webp', 'Wood chop alto para baixo. Ilustração da execução do movimento. Músculo principal: Core. Equipamento: polia.'),
  ('fitos:wood-chop-baixo-para-alto', 'wood-chop-baixo-para-alto.webp', 'Wood chop baixo para alto. Ilustração da execução do movimento. Músculo principal: Core. Equipamento: polia.'),
  ('fitos:world-greatest-stretch', 'world-greatest-stretch.webp', 'World greatest stretch. Ilustração da execução do movimento. Músculo principal: Mobilidade global. Equipamento: colchonete.')
)
UPDATE "exercises" e
SET "imageUrl" = 'https://pub-76bc00d74c5a4bf98ccac51eb4c92de3.r2.dev/' || m.arquivo,
    "imageAlt" = m.alt,
    "updatedAt" = NOW()
FROM manifesto m
WHERE e."origin" = 'FITOS_CURATED'
  AND e."tenantId" IS NULL
  AND e."externalId" = m.external_id
  AND e."imageUrl" IS NULL
;
