import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { appName } from "@/shared/config/env";
import { AppShell } from "@/shared/ui";
import { AuthError, requirePersonal } from "@/modules/tenancy/authContext";
import { listStudents } from "@/modules/students/students";
import { countPendingRecurrencesForMonth, ensureCurrentMonthCharges, getFinancialSummary, listActiveRecurrencesForTenant, listChargesForTenant } from "@/modules/student-finance/charges";
import { currentReferenceMonth, parseReferenceMonth, referenceMonthKey, referenceMonthLabel } from "@/shared/lib/referenceMonth";
import { LogoutButton } from "../LogoutButton";
import { PERSONAL_NAV_ITEMS } from "../navigation";
import { getPaymentAccountSummary } from "@/modules/student-finance/paymentAccount";
import { FinanceiroView, type FinanceTab } from "./FinanceiroView";

export const metadata: Metadata = {
  title: `Financeiro — ${appName}`,
};

interface FinanceiroPageProps {
  searchParams?: Promise<{ mes?: string; aba?: string; nova?: string }>;
}

/// Financeiro do Personal (FIT-148, P6 do protótipo). Competência por
/// `?mes=AAAA-MM` (mês atual quando ausente ou inválida), abas por
/// `?aba=recorrentes` e `?nova=1` abre a nova cobrança (atalho do Início).
export default async function FinanceiroPage({ searchParams }: FinanceiroPageProps = {}) {
  let ctx;
  try {
    ctx = await requirePersonal();
  } catch (error) {
    if (error instanceof AuthError) {
      redirect(error.kind === "UNAUTHENTICATED" ? "/entrar" : "/painel");
    }
    throw error;
  }

  const sp = (await searchParams) ?? {};
  const referenceMonth = parseReferenceMonth(sp.mes) ?? currentReferenceMonth();
  const tab: FinanceTab = sp.aba === "recorrentes" ? "recorrentes" : "cobrancas";
  // Mês corrente: as mensalidades recorrentes se lançam sozinhas (EPIC-29).
  const isCurrentMonth = referenceMonthKey(referenceMonth) === referenceMonthKey(currentReferenceMonth());
  if (isCurrentMonth) await ensureCurrentMonthCharges({ tenantId: ctx.tenantId });

  const [students, summary, charges, recurrences, pendingRecurrences, payments] = await Promise.all([
    listStudents({ tenantId: ctx.tenantId, status: "ATIVO", pageSize: 100 }),
    getFinancialSummary({ tenantId: ctx.tenantId, referenceMonth }),
    listChargesForTenant({ tenantId: ctx.tenantId, referenceMonth }),
    listActiveRecurrencesForTenant({ tenantId: ctx.tenantId }),
    countPendingRecurrencesForMonth({ tenantId: ctx.tenantId, referenceMonth }),
    getPaymentAccountSummary(ctx.tenantId),
  ]);
  const generated = new Set(charges.filter((charge) => charge.recurrenceId).map((charge) => charge.recurrenceId));
  const statusOrder = { ATRASADO: 0, PENDENTE: 1, PAGO: 2, CANCELADO: 3 } as const;

  return (
    <AppShell eyebrow="Financeiro" title="Mensalidades" navItems={PERSONAL_NAV_ITEMS} activeKey="financeiro" trailing={<LogoutButton />}>
      <FinanceiroView
        monthKey={referenceMonthKey(referenceMonth)}
        monthLabel={referenceMonthLabel(referenceMonth)}
        summary={summary}
        charges={[...charges]
          .sort((a, b) => statusOrder[a.status] - statusOrder[b.status] || a.dueDate.getTime() - b.dueDate.getTime())
          .map((charge) => ({
            id: charge.id,
            studentId: charge.student.id,
            studentName: charge.student.displayName,
            description: charge.description,
            amountCents: charge.amountCents,
            dueDate: charge.dueDate.toISOString(),
            status: charge.status,
            cancelReason: charge.cancelReason,
            paidAt: charge.payment?.paidAt.toISOString() ?? null,
            paidCents: charge.payment?.amountCentsPaid ?? null,
            method: charge.payment?.method ?? null,
            paymentUrl: charge.paymentUrl,
            hasCpf: Boolean(charge.student.cpf),
          }))}
        canChargeOnline={payments.connected}
        recurrences={recurrences.map((recurrence) => ({
          id: recurrence.id,
          studentId: recurrence.student.id,
          studentName: recurrence.student.displayName,
          description: recurrence.description,
          amountCents: recurrence.amountCents,
          dueDay: recurrence.dueDayOfMonth,
          generatedThisMonth: generated.has(recurrence.id),
        }))}
        students={students.items.map((student) => ({ id: student.id, displayName: student.displayName }))}
        pendingRecurrences={pendingRecurrences}
        tab={tab}
        startNew={sp.nova === "1"}
        autoGenerated={isCurrentMonth && recurrences.length > 0}
      />
    </AppShell>
  );
}
