-- EPIC-32: catálogo aeróbico completo, a partir do material de referência
-- "Treinos Aeróbicos — Catálogo para o FitOS". Os aeróbicos de antes ganham
-- instruções mais completas (como fazer, variações) e cuidados (erros
-- comuns, impacto, MET aproximado); entram os que faltavam. Idempotente:
-- reaplicar não duplica (ON CONFLICT por origem e externalId).

UPDATE "exercises" SET "instructions" = 'Postura ereta, olhar à frente, passos naturais e braços balançando junto ao corpo. Para subir a intensidade, acelere o passo ou use inclinação. Variações: caminhada intervalada (alternando ritmo).', "safetyInfo" = 'Impacto baixo · MET 3,5–5. Evite passos longos demais, segurar o corrimão e curvar a coluna.', "updatedAt" = NOW() WHERE "id" = 'aerobico_esteira_caminhada';
UPDATE "exercises" SET "instructions" = 'Caminhe com a esteira inclinada entre 6% e 12%, passos firmes e tronco ereto, sem segurar no painel. Ótima para LISS de 30 a 60 min.', "safetyInfo" = 'Impacto baixo · MET 5–7. Reduza a inclinação se sentir dor na lombar ou na panturrilha; não se pendure nas barras.', "updatedAt" = NOW() WHERE "id" = 'aerobico_esteira_inclinada';
UPDATE "exercises" SET "instructions" = 'Tronco levemente inclinado à frente, passada curta e rápida (cerca de 165–180 passos/min), pisada sob o corpo e braços a 90°. Iniciante: alterne 1 min correndo e 2 min caminhando.', "safetyInfo" = 'Impacto alto · MET 8–11,5. Não comece rápido demais nem aumente o volume mais de 10% por semana. Use a trava de segurança da esteira.', "updatedAt" = NOW() WHERE "id" = 'aerobico_esteira_corrida';
UPDATE "exercises" SET "instructions" = 'Ajuste o banco para o joelho ficar levemente flexionado no ponto mais baixo do pedal. Coluna neutra, ombros relaxados, cadência de 70 a 90 rpm.', "safetyInfo" = 'Impacto baixo · MET 5,5–10. Evite banco baixo demais e resistência alta com cadência muito baixa. Boa para joelhos e quadril sensíveis.', "updatedAt" = NOW() WHERE "id" = 'aerobico_bike';
UPDATE "exercises" SET "instructions" = 'Alterne cadência e carga conforme a etapa: sentado, em pé e tiros. Na subida simulada, carga alta e cadência baixa.', "safetyInfo" = 'Impacto baixo · MET 8–10. Mantenha uma carga mínima ao pedalar em pé e os ombros relaxados.', "updatedAt" = NOW() WHERE "id" = 'aerobico_spinning';
UPDATE "exercises" SET "instructions" = 'Postura ereta, apoio leve nas alças, movimento fluido e pés totalmente apoiados nos pedais. Varie para frente e para trás, resistência e inclinação.', "safetyInfo" = 'Impacto muito baixo · MET 5–7. Não apoie o peso nas mãos nem curve o tronco. Boa alternativa à corrida para joelhos sensíveis.', "updatedAt" = NOW() WHERE "id" = 'aerobico_eliptico';
UPDATE "exercises" SET "instructions" = 'Sequência pernas → tronco → braços na puxada e braços → tronco → pernas na volta. Coluna neutra o tempo todo. Variações: contínuo, intervalos de 500 m, pirâmide.', "safetyInfo" = 'Impacto baixo · MET 7–8,5. Não puxe só com os braços, não arredonde as costas e não volte rápido demais.', "updatedAt" = NOW() WHERE "id" = 'aerobico_remo';
UPDATE "exercises" SET "instructions" = 'Pulos baixos (poucos centímetros), aterrissagem na ponta dos pés, cotovelos junto ao corpo e giro com os punhos. Iniciante: 30 s pulando e 30 s de descanso, 8 rodadas.', "safetyInfo" = 'Impacto alto · MET 11–12. Evite pular alto, abrir os braços e aterrissar no calcanhar.', "updatedAt" = NOW() WHERE "id" = 'aerobico_corda';
UPDATE "exercises" SET "instructions" = 'Tronco ereto, passos completos, sem se apoiar totalmente nas alças. Muito eficiente em pouco tempo, com forte ativação de glúteos.', "safetyInfo" = 'Impacto baixo a médio · MET ~9. Não se pendure nas alças nem dê passos curtos e rasos.', "updatedAt" = NOW() WHERE "id" = 'aerobico_escada';
UPDATE "exercises" SET "instructions" = 'Postura ereta, passos naturais e braços acompanhando. Acelere ou procure subidas para intensificar; com bastões, vira caminhada nórdica.', "safetyInfo" = 'Impacto baixo · MET 3,5–5. Hidrate-se e use protetor solar em dias quentes.', "updatedAt" = NOW() WHERE "id" = 'aerobico_caminhada_rua';
UPDATE "exercises" SET "instructions" = 'Passada curta e rápida, pisada sob o corpo, braços a 90°. Variações: contínua leve, fartlek, tiros, subidas e longão.', "safetyInfo" = 'Impacto alto · MET 8–11,5. Progrida no máximo 10% por semana; troque o tênis a cada 600–800 km.', "updatedAt" = NOW() WHERE "id" = 'aerobico_corrida_rua';

INSERT INTO "exercises" ("id", "tenantId", "name", "origin", "status", "externalId", "type", "muscle", "equipments", "difficulty", "instructions", "safetyInfo", "createdAt", "updatedAt")
VALUES
  ('aerobico_natacao', NULL, 'Natação', 'FITOS_CURATED', 'ATIVO', 'fitos:aerobico-natacao', 'Aeróbico', 'Aeróbico', 'piscina', 'intermediario', 'Respiração rítmica, corpo alinhado e horizontal, batida de pernas a partir do quadril e puxada completa dos braços. Varie entre crawl, costas e peito.', 'Impacto muito baixo · MET 6–10. Evite cabeça alta demais e pernas afundando. Ótima para reabilitação e articulações sensíveis.', NOW(), NOW()),
  ('aerobico_hidroginastica', NULL, 'Hidroginástica', 'FITOS_CURATED', 'ATIVO', 'fitos:aerobico-hidroginastica', 'Aeróbico', 'Aeróbico', 'piscina', 'iniciante', 'Movimentos de corrida, chutes e braçadas dentro da água, com a água na altura do peito. A resistência da água trabalha o corpo todo.', 'Impacto muito baixo · MET 4–5,5. Indicada para iniciantes, idosos e quem tem dor articular.', NOW(), NOW()),
  ('aerobico_bike_rua', NULL, 'Ciclismo ao ar livre', 'FITOS_CURATED', 'ATIVO', 'fitos:aerobico-bike-rua', 'Aeróbico', 'Aeróbico', 'bicicleta e capacete', 'iniciante', 'Banco na altura certa (joelho levemente flexionado embaixo), cadência de 70 a 90 rpm e marchas leves nas subidas.', 'Impacto baixo · MET 5,5–10. Use capacete e sinalização; hidrate-se em pedais acima de 45 min.', NOW(), NOW()),
  ('aerobico_trilha', NULL, 'Trilha', 'FITOS_CURATED', 'ATIVO', 'fitos:aerobico-trilha', 'Aeróbico', 'Aeróbico', 'calçado de trilha', 'iniciante', 'Passos firmes, tronco levemente à frente nas subidas e joelhos destravados nas descidas. Combina cardio e força de pernas.', 'Impacto baixo a médio · MET 6–7. Leve água, use protetor solar e avise alguém da rota.', NOW(), NOW()),
  ('aerobico_caminhada_nordica', NULL, 'Caminhada nórdica', 'FITOS_CURATED', 'ATIVO', 'fitos:aerobico-caminhada-nordica', 'Aeróbico', 'Aeróbico', 'bastões', 'iniciante', 'Caminhe empurrando o chão com os bastões, braço oposto à perna da frente, tronco ereto. Envolve braços e ombros na caminhada.', 'Impacto baixo · MET 4,5–6. Ajuste os bastões para o cotovelo ficar a 90°.', NOW(), NOW()),
  ('aerobico_circuito_funcional', NULL, 'Circuito funcional', 'FITOS_CURATED', 'ATIVO', 'fitos:aerobico-circuito-funcional', 'Aeróbico', 'Aeróbico', 'nenhum', 'intermediario', 'Burpee, polichinelo, mountain climber, agachamento com salto e skipping: 40 s de execução e 20 s de descanso em cada, 3 a 4 voltas. Sem equipamento, bom para casa ou viagem.', 'Impacto alto · MET 8–10. Versão de menor impacto: burpee sem salto, polichinelo sem salto e marcha elevada.', NOW(), NOW()),
  ('aerobico_burpee', NULL, 'Burpee', 'FITOS_CURATED', 'ATIVO', 'fitos:aerobico-burpee', 'Aeróbico', 'Aeróbico', 'nenhum', 'intermediario', 'Agache, apoie as mãos, leve os pés para trás em prancha, volte e salte com os braços para cima. Ritmo constante, aterrissagem suave.', 'Impacto alto · MET ~8–10. Sem salto, vira opção de baixo impacto. Mantenha o abdômen firme na prancha.', NOW(), NOW()),
  ('aerobico_polichinelo', NULL, 'Polichinelo', 'FITOS_CURATED', 'ATIVO', 'fitos:aerobico-polichinelo', 'Aeróbico', 'Aeróbico', 'nenhum', 'iniciante', 'Salte abrindo pernas e braços ao mesmo tempo e volte fechando. Aterrisse com os joelhos levemente flexionados.', 'Impacto médio · MET ~8. Sem salto (step jack): abra uma perna de cada vez.', NOW(), NOW()),
  ('aerobico_mountain_climber', NULL, 'Mountain climber', 'FITOS_CURATED', 'ATIVO', 'fitos:aerobico-mountain-climber', 'Aeróbico', 'Aeróbico', 'nenhum', 'intermediario', 'Em prancha alta, leve os joelhos ao peito alternadamente, rápido, sem subir o quadril.', 'Impacto baixo a médio · MET ~8. Mãos sob os ombros e abdômen firme para proteger a lombar.', NOW(), NOW()),
  ('aerobico_skipping', NULL, 'Skipping (joelho alto)', 'FITOS_CURATED', 'ATIVO', 'fitos:aerobico-skipping', 'Aeróbico', 'Aeróbico', 'nenhum', 'iniciante', 'Corra no lugar elevando os joelhos até a altura do quadril, braços acompanhando, pisando com a ponta dos pés.', 'Impacto médio · MET ~8. Versão leve: marcha elevada, sem saltar.', NOW(), NOW()),
  ('aerobico_danca', NULL, 'Dança (dance fitness)', 'FITOS_CURATED', 'ATIVO', 'fitos:aerobico-danca', 'Aeróbico', 'Aeróbico', 'nenhum', 'iniciante', 'Coreografias contínuas no ritmo da música, como Zumba ou aula de aeróbica. Acompanhe os passos básicos e aumente a amplitude aos poucos.', 'Impacto baixo a médio · MET 5–7,5. Divertida e com ótima aderência; use tênis com bom amortecimento.', NOW(), NOW()),
  ('aerobico_boxe', NULL, 'Boxe (shadow boxing)', 'FITOS_CURATED', 'ATIVO', 'fitos:aerobico-boxe', 'Aeróbico', 'Aeróbico', 'luvas e saco de pancada (opcional)', 'intermediario', 'Golpes de jab, direto, gancho e esquivas em rounds de 2 a 3 min com 1 min de descanso, 5 a 8 rounds. Base firme e guarda alta.', 'Impacto baixo a médio · MET 5,5–9. Gire o quadril no golpe e não trave os cotovelos.', NOW(), NOW()),
  ('aerobico_marcha', NULL, 'Marcha estacionária', 'FITOS_CURATED', 'ATIVO', 'fitos:aerobico-marcha', 'Aeróbico', 'Aeróbico', 'nenhum', 'iniciante', 'Marche no lugar com joelhos altos, alternando com step touch, toque de calcanhar e agachamento lateral. Ideal para casa e dias de recuperação.', 'Impacto baixo · MET 3,5–5. Indicada para iniciantes e idosos.', NOW(), NOW())
ON CONFLICT ("origin", "externalId") DO NOTHING;
